/*------------------------------------------------------------------------------
//   This code was generated by template ffi_wrapper.c.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "ffi_wrapper.h.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/
#include <godot/gdextension_interface.h>
#include "ffi_wrapper.gen.h"
#include "stacktrace.h"

/* Go cannot call C function pointers directly, so we must generate C wrapper code to call the functions. */

